export const GET_RECOMMEND_BANNER = 'GET_RECOMMEND_BANNER' 
export const GET_RECOMMEND_HOT = 'GET_RECOMMEND_HOT' 
export const GET_NEW_SONGS = 'GET_NEW_SONGS' 

export const GET_UP_RANKING = 'GET_UP_RANKING' 
export const GET_NEW_RANKING = 'GET_NEW_RANKING' 
export const GET_ORIGIN_RANKING = 'GET_ORIGIN_RANKING' 